name: Shell.sh

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Klont das Repository, um auf den Code und die Dateien zuzugreifen

    - name: Run script
      run: |
            ls -la
            echo "setze rechte"
            chmod +x ./script.sh
            echo "script Ausführung"
            ls -la
            ./script.sh  