name: Shell.sh

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Klont das Repository, um auf den Code und die Dateien zuzugreifen

    - name: update & upgrade
      run: |
        echo "update & upgrade"
        sudo apt-get update 
        sudo apt-get upgrade -y

    - name: Run script
      run: |
            ls -la
            chmod +x script.sh
            ./script.sh  # Führt das Shell-Skript aus