name: Shell.sh

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        
        steps:
        - name: update & upgrade
          run: |
            echo "update & upgrade"
            sudo apt-get update 
            sudo apt-get upgrade -y
       
        - name: Clonen_repository
          run: |
                echo "Clone GitHub-Actions---Shell-Skript_respository"
                git clone https://github.com/DeynesA/GitHub-Actions---Shell-Skript.git

        - name: Shell
          run: ./script.sh